import re


DIFFICULT_WORDS = {
    "utilize": "use",
    "implement": "apply",
    "commence": "start",
    "terminate": "end",
    "numerous": "many",
    "approximately": "about",
    "assistance": "help",
    "attempt": "try",
    "benevolent": "kind",
    "comprehend": "understand",
    "construct": "build",
    "consequently": "so",
    "demonstrate": "show",
    "determine": "find",
    "diminish": "reduce",
    "eliminate": "remove",
    "encounter": "meet",
    "endeavor": "try",
    "enormous": "huge",
    "equivalent": "equal",
    "establish": "set up",
    "evaluate": "judge",
    "examine": "look at",
    "facilitate": "help",
    "frequently": "often",
    "fundamental": "basic",
    "generate": "create",
    "identical": "same",
    "illustrate": "show",
    "immediately": "right away",
    "indicate": "show",
    "individual": "person",
    "initial": "first",
    "investigate": "study",
    "maintain": "keep",
    "modify": "change",
    "obtain": "get",
    "participate": "take part",
    "perceive": "see",
    "perform": "do",
    "possess": "have",
    "preceding": "previous",
    "predict": "guess",
    "primarily": "mainly",
    "proceed": "continue",
    "produce": "make",
    "provide": "give",
    "purchase": "buy",
    "rapid": "fast",
    "require": "need",
    "reside": "live",
    "respond": "answer",
    "retain": "keep",
    "sufficient": "enough",
    "subsequent": "next",
    "substantial": "large",
    "terminate": "stop",
    "transmit": "send",
    "transform": "change",
    "utilization": "use",
    "various": "different",
    "verify": "check",
    "visible": "seen",
    "acquire": "get",
    "additional": "extra",
    "adjacent": "next to",
    "analyze": "study",
    "anticipate": "expect",
    "apparent": "clear",
    "apprehensive": "worried",
    "appropriate": "right",
    "artificial": "man-made",
    "capacity": "ability",
    "circumstance": "situation",
    "collaborate": "work together",
    "compensate": "make up for",
    "complicated": "hard",
    "comprehensive": "complete",
    "concentrate": "focus",
    "conduct": "carry out",
    "confirm": "check",
    "consistent": "steady",
    "contribute": "help",
    "crucial": "important",
    "decrease": "reduce",
    "deficiency": "lack",
    "derive": "get",
    "despite": "even with",
    "detailed": "full",
    "distinguish": "tell apart",
    "efficient": "effective",
    "emphasize": "stress",
    "encourage": "support",
    "essential": "needed",
    "eventually": "finally",
    "exceptional": "special",
    "exclude": "leave out",
    "expand": "grow",
    "expert": "specialist",
    "extensive": "large",
    "familiar": "known",
    "function": "work",
    "identify": "find",
    "improve": "make better",
    "include": "contain",
    "increase": "grow",
    "independent": "alone",
    "interpret": "explain",
    "locate": "find",
    "majority": "most",
    "method": "way",
    "minimum": "least",
    "objective": "goal",
    "occur": "happen",
    "opportunity": "chance",
    "option": "choice",
    "organize": "arrange",
    "particular": "specific",
    "potential": "possible",
    "previously": "before",
    "priority": "importance",
    "process": "steps",
    "recommend": "suggest",
    "relevant": "related",
    "represent": "stand for",
    "significant": "important",
    "similar": "almost the same",
    "solution": "answer",
    "strategy": "plan",
    "temporary": "short-term",
    "therefore": "so",
    "throughout": "during",
    "ultimate": "final",
    "unique": "one of a kind",
    "accurate": "correct",
    "complex": "hard",
    "difficult": "hard",
    "simple": "easy",
    "objective": "goal"
}


def simplify_text(text):
    simplified = text
    for hard, easy in DIFFICULT_WORDS.items():
        simplified = re.sub(rf"\b{hard}\b", easy, simplified, flags=re.IGNORECASE)
    return simplified


def highlight_difficult_words(text):
    highlighted = text
    for hard, easy in DIFFICULT_WORDS.items():
        highlighted = re.sub(
            rf"\b({hard})\b",
            rf'<span class="highlight" title="Meaning: {easy}">\1</span>',
            highlighted,
            flags=re.IGNORECASE
        )
    return highlighted
